### ISSUE TITLE
KeyboardInterrupt starts expensive background process

### ISSUE THREAD

**Issue by ulfaslak** [benmaier/netwulf#4]
This is a weird one. When I `KeyboardInterrupt` in a Jupyter Notebook, a very CPU hungry Python process starts.

![screen shot 2018-11-12 at 14 37 52](https://user-images.githubusercontent.com/6390218/48350811-9ab08300-e688-11e8-81f4-3b0ad06e8e85.png)

When I restart the kernel, it terminates. If I terminate it in the activity monitor, the Jupyter kernel becomes busy (no output in terminal).

Even weirder, if I launch a new visualization, IT STOPS.

**Comment by benmaier** [comment]
possibly fixed (forgot thread.join()). Can you try?

**Comment by benmaier** [comment]
hey @ulfaslak did you have time to test it?

**Comment by ulfaslak** [comment]
Sorry, baby fog, will try later!

**Comment by benmaier** [comment]
sure, no rush! baby's more important :)

**Comment by ulfaslak** [comment]
Alright, it was fast enough to try. So I upgraded with pip to v0.0.6 (right one?), but the bug is still there.

**Comment by benmaier** [comment]
Haven't updated in pip yet, you'd have to install from a cloned repo ..

**Comment by ulfaslak** [comment]
ah on sec

**Comment by ulfaslak** [comment]
ok i'm not being very thorough checking if I installed it right here, but downloading the repo and running `python setup.py install` it installs v 0.0.7, which also imports successfully, but throws the error `DistutilsFileError: cannot copy tree '/anaconda3/lib/python3.7/site-packages/netwulf-0.0.7-py3.7.egg/netwulf/js': not a directory` at `visualize(G)`

**Comment by benmaier** [comment]
cloning probably did not include the submodule then. Can you try

git clone --recurse-submodules git@git....

**Comment by ulfaslak** [comment]
Different behavior now. I interrupt and it doesn't stop, I interrupt it again and it throws error.
![nov-19-2018 13-57-46](https://user-images.githubusercontent.com/6390218/48708582-461a8400-ec03-11e8-8a23-9740e34c0f4b.gif)

**Comment by benmaier** [comment]
ok, off to the to-do pile then. thanks for checking!

**Comment by benmaier** [comment]
is this fixed by now? 🤔

**Comment by benmaier** [comment]
can't reproduce

**Comment by ulfaslak** [comment]
This still happens to me. It's driving me crazy. Also, connected to this, the POST back to Python feature doesn't work. I'll look into this further and we can probably close this for now but jeeeeeesus....

**Comment by benmaier** [comment]
super weird ...

**Comment by ulfaslak** [comment]
It seems to everything right down to line 274 if interactive.py where it hangs on `thread.join()`.

**Comment by benmaier** [comment]
I reopen this ... you won't be the only one having this problem

**Comment by benmaier** [comment]
can you post the specific error message?

**Comment by ulfaslak** [comment]
This is the output when hitting "Post to Python" and then upon returning to the notebook (where the kernel is still busy), interrupting the kernel:

```
changing directory to /Users/ulfaslak/.netwulf
starting server here ... /Users/ulfaslak/.netwulf
127.0.0.1 09/Apr/2019 14:17:27 GET /?data=tmp_16a02081db3.json&config=config_tmp_16a02081db3.json HTTP/1.1 200 -
127.0.0.1 09/Apr/2019 14:17:28 GET /config_tmp_16a02081db3.json HTTP/1.1 200 -
127.0.0.1 09/Apr/2019 14:17:28 GET /tmp_16a02081db3.json HTTP/1.1 200 -
127.0.0.1 09/Apr/2019 14:17:29 POST /?data=tmp_16a02081db3.json&config=config_tmp_16a02081db3.json HTTP/1.1 200 -
Successfully posted network data to Python!
127.0.0.1 09/Apr/2019 14:17:31 POST /?data=tmp_16a02081db3.json&config=config_tmp_16a02081db3.json HTTP/1.1 200 -
stopping server ...
was asked to stop the server
deleted all files
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-6-a227c1684ca5> in <module>
      6     v['group'] = v['block']; del v['block']
      7 
----> 8 visualize(G, verbose=True)

/anaconda3/lib/python3.7/site-packages/netwulf/interactive.py in visualize(network, port, verbose, config)
    272         print('stopping server ...')
    273     server.stop_this()
--> 274     thread.join()
    275 
    276     posted_network_properties = server.posted_network_properties

/anaconda3/lib/python3.7/threading.py in join(self, timeout)
   1030 
   1031         if timeout is None:
-> 1032             self._wait_for_tstate_lock()
   1033         else:
   1034             # the behavior of a negative timeout isn't documented, but

/anaconda3/lib/python3.7/threading.py in _wait_for_tstate_lock(self, block, timeout)
   1046         if lock is None:  # already determined that the C code is done
   1047             assert self._is_stopped
-> 1048         elif lock.acquire(block, timeout):
   1049             lock.release()
   1050             self._stop()

KeyboardInterrupt: 
```

**Comment by ulfaslak** [comment]
I'm on Python 3.7.3, and netwulf version 0.0.14

**Comment by benmaier** [comment]
can you try with the latest commit? I'm pretty sure it won't work but a guy can dream

**Comment by ulfaslak** [comment]
I like your spirit but no cigar. Also, this never runs if you don't interrupt (click Post to Python in webapp)

**Comment by ulfaslak** [comment]
Can it have something to do with the `http.serve_forever()` line? And that it excepts `OSError`s? I tried removing the try-except clause, and nothing happened, but still as I understand it, `thread.join()` is ineffective because `thread` is still busy.

Recall that everything runs smoothly down to and including line 273: `server.stop_this()`

**Comment by benmaier** [comment]
Yeah, I was wondering the same. It's weird though, because `self.server_close()` in line 83 should definitely stop the process.

I'll look into it again in a few days, have to prepare a talk today :/

Here are some links I found which might contain a solution. Using this comment as a bookmark:

https://stackoverflow.com/questions/3788208/threading-ignores-keyboardinterrupt-exception 

https://www.oreilly.com/library/view/python-cookbook/0596001673/ch06s03.html 

https://github.com/agronholm/pythonfutures/pull/50 

https://stackoverflow.com/questions/50891103/after-keyboardinterrupt-except-and-finally-blocks-are-not-executing

https://github.com/eventlet/eventlet/issues/230

http://paste.openstack.org/show/204506/

**Comment by ulfaslak** [comment]
Cool thanks. No stress, just got hung up on this now...

**Comment by benmaier** [comment]
I've added a timeout to `thread.join()` -- can you try again with the new commit?

**Comment by benmaier** [comment]
I now added a functionality which stops `serve_forever`

**Comment by ulfaslak** [comment]
Sweet this works! Causes an error when doing a keyboardinterrupt in Jupyter, made a pull request that fixes this #13 .
